dist: trusty
language: minimal
services:
  - docker

cache:
  directories:
    - vendor

git:
  depth: 1

env:
  matrix:
    - PHP_IMG="base-7.0-mongoext-1.1.5" MONGO_IMG="mongo:3.0" SYMFONY="2.8.*"
    - PHP_IMG="base-7.1-mongoext-1.1.5" MONGO_IMG="mongo:3.0"
    - PHP_IMG="base-7.1-mongoext-1.1.5" MONGO_IMG="mongo:3.2"
    - PHP_IMG="base-7.0-mongoext-1.2.0" MONGO_IMG="mongo:3.0"
    - PHP_IMG="base-7.1-mongoext-1.2.0" MONGO_IMG="mongo:3.0"
    - PHP_IMG="base-7.1-mongoext-1.2.0" MONGO_IMG="mongo:3.2"
    - PHP_IMG="base-7.1-mongoext-1.2.0" MONGO_IMG="mongo:3.4"
    - PHP_IMG="base-7.0-mongoext-1.3.0" MONGO_IMG="mongo:3.2" SYMFONY="3.4.*"
    - PHP_IMG="base-7.0-mongoext-1.3.0" MONGO_IMG="mongo:3.4" TEST_COVERAGE=1
    - PHP_IMG="base-7.1-mongoext-1.3.0" MONGO_IMG="mongo:3.2" SYMFONY="4.*"
    - PHP_IMG="base-7.1-mongoext-1.3.0" MONGO_IMG="mongo:3.4" SYMFONY="dev-master"
    - PHP_IMG="base-7.2-mongoext-1.3.0" MONGO_IMG="mongo:3.2"
    - PHP_IMG="base-7.2-mongoext-1.3.0" MONGO_IMG="mongo:3.4"
    - PHP_IMG="base-7.0-mongoext-1.3.4" MONGO_IMG="mongo:3.2"
    - PHP_IMG="base-7.0-mongoext-1.3.4" MONGO_IMG="mongo:3.4"
    - PHP_IMG="base-7.1-mongoext-1.3.4" MONGO_IMG="mongo:3.2"
    - PHP_IMG="base-7.1-mongoext-1.3.4" MONGO_IMG="mongo:3.4"
    - PHP_IMG="base-7.2-mongoext-1.3.4" MONGO_IMG="mongo:3.2"
    - PHP_IMG="base-7.2-mongoext-1.3.4" MONGO_IMG="mongo:3.4"
    - PHP_IMG="base-7.0-mongoext-1.4.2" MONGO_IMG="mongo:3.6"
    - PHP_IMG="base-7.1-mongoext-1.4.2" MONGO_IMG="mongo:3.4"
    - PHP_IMG="base-7.1-mongoext-1.4.2" MONGO_IMG="mongo:3.6"
    - PHP_IMG="base-7.2-mongoext-1.4.2" MONGO_IMG="mongo:3.4"
    - PHP_IMG="base-7.2-mongoext-1.4.2" MONGO_IMG="mongo:3.6"
    - PHP_IMG="base-7.0-mongoext-1.5.3" MONGO_IMG="mongo:4.0"
    - PHP_IMG="base-7.1-mongoext-1.5.3" MONGO_IMG="mongo:3.6"
    - PHP_IMG="base-7.1-mongoext-1.5.3" MONGO_IMG="mongo:4.0"
    - PHP_IMG="base-7.2-mongoext-1.5.3" MONGO_IMG="mongo:3.6"
    - PHP_IMG="base-7.2-mongoext-1.5.3" MONGO_IMG="mongo:4.0"
    - PHP_IMG="base-7.2-mongoext-1.5.3" MONGO_IMG="percona/percona-server-mongodb:4.0"
    - PHP_IMG="base-7.3-mongoext-1.5.3" MONGO_IMG="mongo:3.6"
    - PHP_IMG="base-7.3-mongoext-1.5.3" MONGO_IMG="mongo:4.0"
    - PHP_IMG="base-7.3-mongoext-1.5.3" MONGO_IMG="percona/percona-server-mongodb:4.0"

matrix:
  fast_finish: true
  allow_failures:
    - env: PHP_IMG="base-7.1-mongoext-1.3.0" MONGO_IMG="mongo:3.4" SYMFONY="dev-master"

install:
  - rm docker-compose.yml
  - mv docker-compose.travis.yml docker-compose.yml
  - sudo chmod -R 777 . # ugly! Travis is 2000:2000
  - |
    if [ "$SYMFONY" != "" ]; then
      if [[ "$SYMFONY" = "dev-master" ]]; then
        docker-compose run --no-deps --rm php-cli composer config minimum-stability dev
      fi;
      docker-compose run --no-deps --rm php-cli composer require "symfony/symfony:${SYMFONY}" --no-update;
    fi;
  - docker-compose run --no-deps --rm php-cli composer install --prefer-dist --no-interaction ${COMPOSER_FLAGS}

script:
  - docker-compose run --no-deps --rm php-cli composer validate
  - |
    if [[ "$TEST_COVERAGE" = "1" ]]; then
      docker-compose run --rm php-cli bash -c "sleep 3; bin/phpunit -c phpunit.xml.dist --coverage-clover=./build/coverage/coverage.clover"
    else
      docker-compose run --rm php-cli bash -c "sleep 3; bin/phpunit -c phpunit.xml.dist"
    fi

after_success:
  - |
    if [[ "$TEST_COVERAGE" = "1" ]]; then
      wget https://scrutinizer-ci.com/ocular.phar --output-document="${HOME}/bin/ocular"; \
      chmod +x "${HOME}/bin/ocular"; \
      ocular code-coverage:upload --format=php-clover ./build/coverage/coverage.clover
    fi

notifications:
  on_success: change
  on_failure: change
