version: "3.1"

services:
  php-cli:
    image: algatux/php-cli-mongodb:1.1
    volumes:
    - ./:/home/user-dev/project
    tty: true
    depends_on:
    - mongo
    container_name: mb_php
  mongo:
    image: mongo:3.4.2
    environment:
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=rootPass
    container_name: mb_mongo
